name: Keep Render Active

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Frontend
        run: curl https://no-fake-samachar.onrender.com

      - name: Ping Backend
        run: curl https://no-fake-samacharbackend.onrender.com

      - name: Ping ML Service
        run: curl https://no-fake-samachar-mlservice.onrender.com
